{{cookiecutter.project_slug}}/users/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

app_name = "users"

urlpatterns = [
    url(
        regex=r'^list/$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^dashboard/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

{{cookiecutter.project_slug}}/utils/models.py
from django.db import models

from wagtail.admin.edit_handlers import (
    FieldPanel, MultiFieldPanel, PageChooserPanel
)
from wagtail.core.fields import RichTextField
from wagtail.documents.edit_handlers import DocumentChooserPanel
from wagtail.images.edit_handlers import ImageChooserPanel


class LinkFields(models.Model):
    link_external = models.URLField("External link", blank=True)
    link_page = models.ForeignKey(
        'wagtailcore.Page',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )
    link_document = models.ForeignKey(
        'wagtaildocs.Document',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    @property
    def link(self):
        if self.link_page:
            return self.link_page.url
        elif self.link_document:
            return self.link_document.url
        else:
            return self.link_external

    panels = [
        FieldPanel('link_external'),
        PageChooserPanel('link_page'),
        DocumentChooserPanel('link_document'),
    ]

    class Meta:
        abstract = True


class ContactFields(models.Model):
    name_organization = models.CharField(max_length=255, blank=True)
    telephone = models.CharField(max_length=20, blank=True)
    telephone_2 = models.CharField(max_length=20, blank=True)
    email = models.EmailField(blank=True)
    email_2 = models.EmailField(blank=True)
    address_1 = models.CharField(max_length=255, blank=True)
    address_2 = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=255, blank=True)
    country = models.CharField(max_length=255, blank=True)
    post_code = models.CharField(max_length=10, blank=True)

    panels = [
        FieldPanel('name_organization',
                   'The full/formatted name of the person or organisation'),
        FieldPanel('telephone'),
        FieldPanel('telephone_2'),
        FieldPanel('email'),
        FieldPanel('email_2'),
        FieldPanel('address_1'),
        FieldPanel('address_2'),
        FieldPanel('city'),
        FieldPanel('country'),
        FieldPanel('post_code'),
    ]

    class Meta:
        abstract = True


# Carousel items

class CarouselItem(LinkFields):
    image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )
    embed_url = models.URLField("Embed URL", blank=True)
    caption = RichTextField(blank=True)

    panels = [
        ImageChooserPanel('image'),
        FieldPanel('embed_url'),
        FieldPanel('caption'),
        MultiFieldPanel(LinkFields.panels, "Link"),
    ]

    class Meta:
        abstract = True


# Related links

class RelatedLink(LinkFields):
    title = models.CharField(max_length=255, help_text="Link title")

    panels = [
        FieldPanel('title'),
        MultiFieldPanel(LinkFields.panels, "Link"),
    ]

    class Meta:
        abstract = True

{{cookiecutter.project_slug}}/utils/templates/utils/tags/navigation/account.html
{% raw %}{% load i18n %}
{% if request.user.is_authenticated %}
  <a id="user" type="button" data-toggle="admin-dropdown">
    <i class="fa fa-user"></i>&nbsp;
    {% if request.user.name %}
      {{ request.user.name }}
    {% else %}
      {{ request.user.username }}
    {% endif %}
  </a>
  <div class="dropdown-pane small" id="admin-dropdown" data-dropdown data-hover="true" data-hover-pane="true">
    <li>
      <a href="{% url 'users:detail' %}"><i class="fa fa-id-card"></i>&nbsp; Dashboard</a>
    </li>
    <li>
      <a href="{% url 'users:update' %}"><i class="fa fa-pencil-alt"></i>&nbsp; Edit Profile</a>
    </li>
    <li>
      <a href="{% url 'account_email' %}"><i class="fa fa-envelope"></i>&nbsp; Email Settings</a>
    </li>
    <li>
      <a href="{% url 'account_change_password' %}"><i class="fa fa-key"></i>&nbsp; Change Passsword</a>
    </li>
    {% if request.user.is_superuser %}
    <li>
      <a href="/admin"><i class="fa fa-user"></i>&nbsp; Admin</a>
    </li>
    {% endif %}
    <hr>
    <li>
      <a href="{% url 'account_logout' %}"><i class="fa fa-sign-out-alt"></i>&nbsp; {% trans "Sign out" %}</a>
    </li>
  </div>
{% else %}
  <a id="sign-up-link" href="{% url 'account_signup' %}">
    <i class="fa fa-edit"></i>&nbsp; {% trans "Sign Up" %}
  </a>

  <a id="log-in-link" href="{% url 'account_login' %}" >
    <i class="fa fa-sign-in-alt"></i>&nbsp; {% trans "Login" %}
  </a>
{% endif %}{% endraw %}

{{cookiecutter.project_slug}}/utils/templates/utils/tags/navigation/breadcrumbs.html
{% raw %}{% load wagtailcore_tags %}

<div class="grid-container">
	<div class="grid-x grid-padding-x hide-for-print">
		<div class="medium-12 cell">
	    	{% if ancestors %}
	    		<nav aria-label="You are here:" role="navigation">
	      			<ul class="breadcrumbs">
	        			<li><a href="/"> Home</a></li>
	        			{% for ancestor in ancestors %}
	        				{% if forloop.last %}
	        					<li class="current">{{ ancestor }}</li>
	        				{% else %}
	        					<li><a href="{% pageurl ancestor %}">{{ ancestor }}</a></li>
	        				{% endif %}
	        			{% endfor %}
	      			</ul>
	    		</nav>
	    	{% endif %}
	  	</div>
	</div>
</div>{% endraw %}

{{cookiecutter.project_slug}}/utils/templates/utils/tags/navigation/offcanvas_top_menu.html
{% raw %}{% load wagtailcore_tags navigation_tags wagtailsettings_tags static %}
{% get_settings %}
{% get_site_root as site_root %}

<div id="social_bar" class="hide-for-print">
	<div class="grid-container" style="max-width: 100%;">
    	{% include "contact/includes/social.html" %}
			{% comment %}
			{% include "utils/tags/navigation/account.html" %}
			{% endcomment %}
  	</div>
</div>

<div class="off-canvas-wrapper">
  	<div class="title-bar hide-for-print">
    	<div class="title-bar-left">
      		<button class="menu-icon" type="button" data-toggle="offCanvas"></button>
      		<span class="title-bar-title"><a href="{% pageurl site_root %}" style="color: #fff;">ChrisDev Wagtail</a></span>
    	</div>
  	</div>
  	<div class="off-canvas position-left hide-for-print" id="offCanvas" data-off-canvas>
    	<button class="close-button" aria-label="Close menu" type="button" data-close>
      		<span aria-hidden="true">&times;</span>
    	</button>
    	<ul class="vertical menu" data-drilldown>
      		<li><a href="{% pageurl site_root %}">Home</a></li>
	  			{% for menuitem in menuitems %}
	      			<li>
	        			<a href="{% pageurl menuitem %}">{{ menuitem.title }}</a>
	        				{% if menuitem.show_dropdown %}
	        					<ul class="menu vertical nested">
	          						<li><a href="{% pageurl menuitem %}">{{ menuitem.title }}</a></li>
	          						{% offcanvas_top_menu_children parent=menuitem %}
	        					</ul>
	        				{% endif %}
	      			</li>
	  			{% endfor %}
    	</ul>
  	</div>
</div>{% endraw %}

{{cookiecutter.project_slug}}/utils/templates/utils/tags/navigation/offcanvas_top_menu_children.html
{% raw %}{% load wagtailcore_tags navigation_tags %}

{% for child in menuitems_children %}
	<li>
  		<a href="{% pageurl child %}">{{ child.title }}</a>
  		{% if child.show_dropdown %}
  			<ul class="menu vertical nested">
    			<li><a href="{% pageurl child %}">{{ child.title }}</a></li>
    			{% top_menu_children parent=child %}
  			</ul>
  		{% endif %}
	</li>
{% endfor %}{% endraw %}

{{cookiecutter.project_slug}}/utils/templates/utils/tags/navigation/secondary_menu.html
{% raw %}{% load wagtailcore_tags %}

{% if pages %}
	<div class="grid-x grid-padding-x hide-for-print">
  		<div class="medium-12 cell">
    		<div id="side_menu" class="card" style="padding-bottom: 15px;">
      			<center><h6 class="title" style="font-variant: small-caps;"><strong>Also In This Section</strong></h6></center>
      			<ul class="menu vertical">
        			{% for page in pages %}
        				<li style="font-size: 14px;"><a href="{% pageurl page %}"><strong>{{ page.title }}</strong></a></li>
        			{% endfor %}
      			</ul>
    		</div>
  		</div>
	</div>
{% endif %}{% endraw %}

{{cookiecutter.project_slug}}/utils/templates/utils/tags/navigation/secondary_menu_grid.html
{% raw %}{% load wagtailcore_tags wagtailimages_tags wagtailimages_tags %}
{% if pages %}
	<div class="grid-x grid-padding-x medium-up-3" data-equalizer>
        {% for page in pages %}
            <div class="cell">
                <a href="{% pageurl page %}">
                    <div class="card">
                        {% if page.specific.feed_image %}
                            {% image page.specific.feed_image fill-1200x700 %}
                        {% endif %}
                        <div class="card-section text-center" style="padding: 8px;">
                            <h5>{{ page.title }}</h5>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endif %}{% endraw %}

{{cookiecutter.project_slug}}/utils/templates/utils/tags/navigation/site_menu.html
{% raw %}{% load wagtailcore_tags navigation_tags %}
{% get_site_root as site_root %}

<ul class="vertical menu accordion-menu" data-accordion-menu>
  	{% for menuitem in menuitems %}
  		<li><a href="{% pageurl menuitem %}">{{ menuitem.title }}</a>
  			{% if menuitem.show_dropdown %}
  				<ul class="menu vertical nested">
    				{% site_menu_children parent=menuitem %}
  				</ul>
  			{% endif %}
  		</li>
  {% endfor %}
</ul>{% endraw %}

{{cookiecutter.project_slug}}/utils/templates/utils/tags/navigation/site_menu_children.html
{% raw %}{% load wagtailcore_tags navigation_tags %}

{% for child in menuitems_children %}
	<li><a href="{% pageurl child %}">{{ child.title }}</a></li>
{% endfor %}{% endraw %}

{{cookiecutter.project_slug}}/utils/templates/utils/tags/navigation/top_menu.html
{% raw %}{% load wagtailcore_tags navigation_tags i18n wagtailsettings_tags static %}
{% get_settings %}
{% get_site_root as site_root %}

<div class="hide-for-print" data-sticky-container>
<div data-sticky data-options="marginTop:0;" style="width:100%;z-index:10000;">

	<div id="social_bar">
  		<div class="grid-container" style="max-width: 100%;">
    		{% include "contact/includes/social.html" %}
				{% comment %}
				{% include "utils/tags/navigation/account.html" %}
				{% endcomment %}
  		</div>
	</div>

	<div class="title-bar" data-responsive-toggle="menu" data-hide-for="large">
  		<button class="menu-icon" type="button" style="background: transparent;"data-toggle></button>
  		<div class="title-bar-title"><a href="{% pageurl site_root %}">Wagtail</a></div>
	</div>

    <div class="top-bar" id="menu">
      	<div class="top-bar-left hide-for-small-only">
        	<ul class="dropdown menu">
          		<li class="menu-text"><a href="{% pageurl site_root %}" style="padding: 0;">Wagtail</a></li>
        	</ul>
      	</div>
      	<div class="top-bar-right">
        	<ul class="vertical medium-horizontal menu" data-responsive-menu="drilldown medium-dropdown">
          		<li class="{% if calling_page.url == site_root %} is-active{% endif %}"><a href="{% pageurl site_root %}">Home</a></li>
          		{% for menuitem in menuitems %}
          			<li class="{% if menuitem.show_dropdown %}has-submenu{% endif %}">
            			<a href="{% pageurl menuitem %}">{{ menuitem.title }}</a>
            				{% if menuitem.show_dropdown %}
            					<ul class="submenu menu vertical" data-submenu>
            						<li class="show-for-small-only">
            							<a href="{% pageurl menuitem %}">{{ menuitem.title }}</a>
            						</li>
              						{% top_menu_children parent=menuitem %}
            					</ul>
            				{% endif %}
            		</li>
            	{% endfor %}
          		<li class="has-form show-for-small-only" style="background: transparent;">
            		<form action ="{% url 'search' %}" method="get">
              			<div class="row collapse">
                			<div class="small-8 columns">
                  				<input class="field" type="text" placeholder="Search" name="q"{% if query_string %} value="{{ query_string }}"{% endif %}>
                			</div>
                			<div class="small-4 columns">
                  				<input type="submit" class="button expand" value="Search">
                			</div>
              			</div>
            		</form>
          		</li>
        	</ul>
      	</div>
    </div>

</div>
</div>{% endraw %}

{{cookiecutter.project_slug}}/utils/templates/utils/tags/navigation/top_menu_children.html
{% raw %}{% load wagtailcore_tags navigation_tags %}

{% for child in menuitems_children %}
	<li class="{% if child.show_dropdown %}has-submenu{% endif %}{% if calling_page.url == child.url %} is-active{% endif %}">
  		<a href="{% pageurl child %}">{{ child.title }}</a>
  		{% if child.show_dropdown %}
  			<ul class="submenu menu vertical">
    			{% top_menu_children parent=child %}
  			</ul>
  		{% endif %}
	</li>
{% endfor %}{% endraw %}